### PR TITLE
Fixed build error caused due to FAQ

### PR DESCRIPTION
**Pull request by harshil1712**

### CODE REVIEW

**Comment by ajayns** [comment]
Hey @harshil1712 ! Thank you for the PR! I was thinking since we follow the convention of naming files in camelCase maybe we should rename `FAQ.js` to `Faq.js`. @apollonian opinions?

**Comment by ajayns** [comment]
Also, it'd be great if we can add this repo to netlify to see PR live previews @apollonian

**Comment by apollonian** [comment]
@ajayns Yep! That sounds good. @harshil1712 Can you rename the file please? 
Also, I'll turn the deploy previews on. ✌️

**Comment by harshil1712** [comment]
@apollonian sure. I'll make the changes

**Comment by ajayns** [comment]
🎉

**Comment by ajayns** [comment]
Thank you @harshil1712 :)

**Pull request merged**
