### PR TITLE
Updated the README.md by changing the yarn commands

### PR DESCRIPTION
**Pull request by richard937**
I have changed all the yarn commands that are written as heading into a code snippet

### CODE REVIEW

**Comment by ajayns** [comment]
They're written as emphasized code snippets so it can be clearly read and understood. Is there any benefit in converting them into smaller code-snippets?

**Comment by richard937** [comment]
Actually there was an issue regarding this that's why I changed it, and the possible reason could be like it was looking very odd in capital.  So changing it would give it a more clean and professional look.

**Comment by ajayns** [comment]
It looking odd is a subjective opinion. As of now, it is clean and clear and has no issues with legibility. Unless you can find any guidelines/rules regarding or actual problematic issues, we'd like to keep it as is.

**Comment by richard937** [comment]
sure...I would look for such issues

**Pull request merged**
