### PR TITLE
fixed dependency issues

### PR DESCRIPTION
**Pull request by csleong98**

### CODE REVIEW

**Comment by ajayns** [comment]
Hey @csleong98 can you please elaborate on what issue you fixed exactly?

**Comment by itaditya** [comment]
More details why its necessary here- https://github.com/gatsbyjs/gatsby/issues/13635#issuecomment-486894353

**Comment by ajayns** [comment]
@csleong98 Okay. Can you please fix the merge conflicts so that we can move forward with the checks and merge?

**Comment by csleong98** [comment]
@ajayns It is done

**Comment by ajayns** [comment]
Thanks a bunch :) @csleong98

**Pull request merged**
